import os
from auditor import calculate_variances
from researcher import ResearchAgent

def run_finance_pipeline():
    print("Starting Financial Analysis Agent...")
    
    # Step 1: Run Math (Auditor)
    # This pulls data from your CSVs and finds the overspends
    flagged_variances = calculate_variances()
    
    if not flagged_variances:
        print("No material variances found. Everything is within budget.")
        return

    # Step 2: Initialize Researcher
    api_key = os.getenv("GROQ_API_KEY") or os.getenv("OS_API_KEY")
    if not api_key:
        print("Missing API key. Set GROQ_API_KEY (preferred) or OS_API_KEY in your environment.")
        return

    researcher = ResearchAgent(api_key=api_key)
    
    final_report = []
    
    # Step 3: Loop through issues and explain them
    for item in flagged_variances:
        print(f"Researching {item['category']}...")
        explanation = researcher.explain_variance(item['category'], item['variance'])
        
        report_entry = {
            "Category": item['category'],
            "Variance": f"${item['variance']}",
            "Analysis": explanation
        }
        final_report.append(report_entry)
    
    # Step 4: Output Final Narrative
    print("\n--- FINAL CFO NARRATIVE REPORT ---")
    print("Generated by: Autonomous FP&A Agent")
    print("-" * 35)
    
    for entry in final_report:
        print(f"\nITEM: {entry['Category']} ({entry['Variance']} Over)")
        print(f"EXPLANATION: {entry['Analysis']}")
        
    print("\n--- END OF REPORT ---")

if __name__ == "__main__":
    run_finance_pipeline()